version = 1

[[annotations]]
path = "src/vendor/**"
precedence = "override"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "NOASSERTION"

[[annotations]]
path = [
  "src/static/**",
  "src/templates/**",
  "src/db/migrations/**",
  "src/go.mod",
  "src/go.sum",
  "flake.lock",
  ".envrc",
  ".gitignore",
  "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Humaid Alqasimi"
SPDX-License-Identifier = "Apache-2.0"

